### PR TITLE
Fixed wrong modIds

### PR DESCRIPTION
**Pull request by HttpRafa**

### CODE REVIEW

**Comment by warior456** [comment]
do the textures still work with this?

**Comment by HttpRafa** [comment]
Before the change, there was a missing texture (this pink/black) and there was an error in the console. Now the textures works again and the error no longer appears in the console. I think that was just forgotten.

**Comment by AlexNijjar** [comment]
This branch is getting deleted, as I am porting fresh from 1.18. I'll keep this in mind when I port again, though.

**Comment by HttpRafa** [comment]
Ok no problem

**Pull request merged**
