### PR TITLE
Lunarian trade recipe

### PR DESCRIPTION
**Pull request by gisellevonbingen**
# Summary

1. Add config whether enable/disable lunarian and lunarian wandering trader's default trades.
1. Add recipe system to add lunarian trades.

# Config 'Lunarian Default Trades'

image

1. Show trades only added by json file if disabled.

# Recipe json format and Examples

### Types

|Order|Name|Selling|
|-:|-|-|
|1|ad_astra:lunarian_trade_simple|Static itemstacks|
|2|ad_astra:lunarian_trade_enchanted_book|'Enchatned Book' with random enchant |
|3|ad_astra:lunarian_trade_enchanted_item|Itemstack with random enchant|
|4|ad_astra:lunarian_trade_dyed_item|Itemstack with dyed random color|
|5|ad_astra:lunarian_trade_potioned_item|Itemstack with random potion effect<br>(e.g. Tipped Arrow)|
|7|ad_astra:lunarian_trade_suspicious_stew|Itemstack having MobEffect<br>(e.g. Suspicious Stew)|

### Common scheme

|Order|Property|Type|Description|
|-:|-|-|-|
|1|type|String|One recipe type in above|
|2|profession*|String|Lunarian's job<br>e.g.) minecraft:armorer<br>Not required, Default is empty|
|3|wandering*|Boolean|Whether for lunarian wandering trader<br>Not required, Default is false|
|4|level|Int|Lunarian's job level<br>Or wandering trader's trade 'pool number'**|
|5|buyA|ItemStack|First itemstack to buy<br>Detail spec is difference by type|
|6|buyB|ItemStack|Secend itemstack to buy<br>Detail spec is difference by type<br>Not required mostly|
|7|sell|ItemStack|Selling itemstack<br>Detail spec is difference by type|
|8|maxUses|Int|Trade count per stock<br>Not required, Default is 12|
|9|experience|Int|Lunarian's earned experience amount when trade<br>Not required, Default is 0|
|10|multiplier|Float|Multiplied by buyA's count according gossip<br>Not required, Default is 0.05|

\* Must set 'wandering is true' or define profession.
** 'Pool number' when 'wandering' set as true,
0: Choice up to 5 'trade' randomly in this pool .
1: Choice one 'trade' randomly in this pool.

## 1. lunarian_trade_simple

Sell static itemstacks

### Scheme

|Order|Property|Type|Description|
|-:|-|-|-|
|1|type|String|ad_astra:lunarian_trade_simple|
|2|buyA|ItemStack|First itemstack to buy<br>Required|
|3|buyB|ItemStack|Secend itemstack to buy<br>Not required mostly|
|4|sell|ItemStack|Selling itemstack<br>Required|

### Examples

```json
{
	"type":"ad_astra:lunarian_trade_simple",
	"profession": "minecraft:armorer",
	"level": 1,
	"maxUses": 1,
	"experience": 10,
	"buyA": "minecraft:diamond",
	"sell": {
		"id":"minecraft:emerald",
		"count":32
	}
}
```
image

```json
{
	"type":"ad_astra:lunarian_trade_simple",
	"wandering": true,
	"level": 1,
	"maxUses": 1,
	"experience": 10,
	"buyA": {
		"id": "minecraft:arrow",
		"count": 16
	},
	"buyB": "minecraft:bow",
	"sell": "minecraft:experience_bottle"
}
```
image

## 2. lunarian_trade_enchanted_book

Sell 'Enchatned Book' with random enchant

### Scheme

Undefined properties are inherit from common scheme

|Order|Property|Type|Description|
|-:|-|-|-|
|1|type|String|ad_astra:lunarian_trade_enchanted_book|
|2|buyA|ItemStack|First itemstack to buy<br>Required, but count will be override by choiced enchantment and internal expression<br>Default is minecraft:emerald|
|3|buyB|ItemStack|Secend itemstack to buy<br>Not required<br>Default is minecraft:book|
|4|sell|ItemStack|Unused|
|5|maxUses|Int|Trade count per stock<br>Not required, Default is 12|
|6|multiplier|Float|Multiplied by buyA's count according gossip<br>Not required, Default is 0.20|

### Examples

```json
{
	"type":"ad_astra:lunarian_trade_enchanted_book",
	"profession": "minecraft:librarian",
	"level": 1
}
```
image

```json
{
	"type":"ad_astra:lunarian_trade_enchanted_book",
	"profession": "minecraft:librarian",
	"level": 1,
	"maxUses": 1,
	"experience": 10,
	"buyA": "minecraft:paper",
	"buyB": {
		"id": "minecraft:emerald",
		"count": 2
	}
}
```
image

## 3. lunarian_trade_enchanted_item

Sell itemstack with random enchant

### Scheme

Undefined properties are inherit from common scheme

|Order|Property|Type|Description|
|-:|-|-|-|
|1|type|String|ad_astra:lunarian_trade_enchanted_item|
|2|buyA|ItemStack|First itemstack to buy<br>Required, but count will be override by choiced enchantment  and internal expression<br>Default is minecraft:emerald|
|3|buyB|ItemStack|Secend itemstack to buy<br>Not required|
|4|sell|ItemStack|Selling itemstack with enchantment|
|5|basePrice|Int|Minimum of buyA's count|
|6|multiplier|Float|Multiplied by buyA's count according gossip<br>Not required, Default is 0.05|

### Examples

```json
{
	"type":"ad_astra:lunarian_trade_enchanted_item",
	"profession": "minecraft:armorer",
	"level": 2,
	"sell": "minecraft:iron_sword",
	"basePrice": 10
}
```

image

## 4. lunarian_trade_dyed_item

Sell itemstack with dyed random color

### Scheme

Undefined properties are inherit from common scheme

|Order|Property|Type|Description|
|-:|-|-|-|
|1|type|String|ad_astra:lunarian_trade_dyed_book|
|2|buyA|ItemStack|First itemstack to buy|
|3|buyB|ItemStack|Secend itemstack to buy<br>Not required|
|4|sell|ItemStack|Selling itemstack with dyed|
|5|maxUses|Int|Trade count per stock<br>Not required, Default is 12|
|6|experience|Int|Lunarian's earned experience amount when trade<br>Not required, Default is 1|
|7|multiplier|Float|Multiplied by buyA's count according gossip<br>Not required, Default is 0.2|

### Examples

```json
{
	"type":"ad_astra:lunarian_trade_dyed_item",
	"profession": "minecraft:armorer",
	"level": 1,
	"maxUses": 99,
	"experience": 100,
	"buyA": "minecraft:diamond",
	"sell": "ad_astra:space_suit"
}
```
image

## 5. lunarian_trade_potioned_item

Sell itemstack with random potion effect
(e.g. Tipped Arrow)

### Scheme

Undefined properties are inherit from common scheme

|Order|Property|Type|Description|
|-:|-|-|-|
|1|type|String|ad_astra:lunarian_trade_potioned_item|
|2|buyA|ItemStack|First itemstack to buy|
|3|buyB|ItemStack|Secend itemstack to buy<br>Not required|
|4|sell|ItemStack|Selling itemstack holding potion effect|
|5|multiplier|Float|Multiplied by buyA's count according gossip<br>Not required, Default is 0.05|

### Examples

```json
{
	"type":"ad_astra:lunarian_trade_potioned_item",
	"profession": "minecraft:fletcher",
	"level": 1,
	"buyA": {
		"id": "minecraft:emerald",
		"count": 3
	},
	"buyB": {
		"id": "minecraft:arrow",
		"count": 30
	},
	"sell": {
		"id": "minecraft:tipped_arrow",
		"count": 30
	}
}
```
image

## 6. lunarian_trade_suspicious_stew

Sell itemstack having MobEffect
(e.g. Suspicious Stew)

### Scheme

Undefined properties are inherit from common scheme

|Order|Property|Type|Description|
|-:|-|-|-|
|1|type|String|ad_astra:lunarian_trade_suspicious_stew|
|2|buyA|ItemStack|First itemstack to buy|
|3|buyB|ItemStack|Secend itemstack to buy<br>Not required|
|4|sell|ItemStack|Selling itemstack holding potion effect<br>Not required, Default is minecraft:suspicious_stew|
|5|mobEffect|String|Mob effect registry name<br>e.g.) minecraft:luck
|6|duration|Int|Effect duration [ticks]|
|7|maxUses|Int|Trade count per stock<br>Not required, Default is 12|
|8|multiplier|Float|Multiplied by buyA's count according gossip<br>Not required, Default is 0.05|

### Examples

```json
{
	"type":"ad_astra:lunarian_trade_suspicious_stew",
	"wandering": true,
	"level": 1,
	"maxUses": 1,
	"buyA": "minecraft:bowl",
	"mobEffect": "minecraft:night_vision",
	"duration": 2000
}
```
image
image

### CODE REVIEW

**Review by AlexNijjar — COMMENTED** [review]
😮 this is really nice! We were planning on making trades data-generated and a lot of people were asking how to change it. thank you!

is it possible to set the nbt in json? so for example can I make them sell a full oxygen tank?

also how about instead of a config, the default trades can be recipes by default, and then packs can override those trades instead of disabling them in the config. So this https://github.com/gisellevonbingen/Minecraft-Ad-Astra/blob/1.19-LunarianTradeRecipe/common/src/main/java/earth/terrarium/ad_astra/common/entity/LunarianMerchantOffer.java would be a recipe by default

**Comment by gisellevonbingen** [comment]
Nbt can be defined as 'nbt' property following Resourcefullib' ItemStack codec.
Oxygen Tank and other Ad Astra!'s item's fluid /energy tag is following Botarium nbt format.

## Nbt Example 1 - Oxygen Tank
```json
{
	"type":"ad_astra:lunarian_trade_simple",
	"profession": "minecraft:armorer",
	"level": 1,
	"maxUses": 1,
	"experience": 10,
	"buyA": {
		"id":"minecraft:emerald",
		"count":32
	},
	"sell": {
		"id":"ad_astra:oxygen_tank",
		"nbt": {
			"BotariumData": {
				"StoredFluids": [
					{
						"Fluid": "ad_astra:oxygen",
						"Amount": 300
					}
				]
			}
		}
	}
}
```
image

## Nbt Example 2 - Jet Suit
```json
{
	"type":"ad_astra:lunarian_trade_simple",
	"profession": "minecraft:armorer",
	"level": 1,
	"maxUses": 1,
	"experience": 10,
	"buyA": {
		"id":"minecraft:emerald",
		"count":32
	},
	"sell": {
		"id":"ad_astra:jet_suit",
		"nbt": {
			"BotariumData": {
				"Energy": 987654,
				"StoredFluids": [
					{
						"Fluid": "ad_astra:oxygen",
						"Amount": 1234
					}
				]
			}
		}
	}
}
```
image

**Comment by gisellevonbingen** [comment]
> So this https://github.com/gisellevonbingen/Minecraft-Ad-Astra/blob/1.19-LunarianTradeRecipe/common/src/main/java/earth/terrarium/ad_astra/common/entity/LunarianMerchantOffer.java would be a recipe by default

Yeah, i wanted them ported to recipe jsons.
I will do that gradly.

About config, maybe it need for when disable all default trade at once.

**Comment by gisellevonbingen** [comment]
OK, i implemented LunarianTradeRecipe generation system. instead of write json file manually of every trade.
Need 'forge:runData' task in gradle, before Test/Release.

Also via RecipeCondition, that recipes can disabled by config.

**Pull request merged**
